import { Card } from '@/components/ui/card';
import { PageHeader } from '@/components/ui/page-header';
import { API_URL } from '@/lib/api-client';
export default async function ReceiptPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  return (
    <div className="space-y-7">
      <PageHeader
        eyebrow="Receipt"
        title="Payment receipt"
        description="The PDF is generated by the server and protected by resident ownership checks."
      />
      <Card>
        <a
          className="font-semibold text-blue-700"
          href={`${API_URL}/receipts/${id}`}
        >
          Download PDF receipt
        </a>
      </Card>
    </div>
  );
}
