export const ROLE_CODES = {
  SUPER_ADMINISTRATOR: 'SUPER_ADMINISTRATOR',
  ADMINISTRATOR: 'ADMINISTRATOR',
  ACCOUNTS_MANAGER: 'ACCOUNTS_MANAGER',
  MAINTENANCE_MANAGER: 'MAINTENANCE_MANAGER',
  RESIDENT: 'RESIDENT',
  SECURITY_GUARD: 'SECURITY_GUARD',
} as const;

export type RoleCode = (typeof ROLE_CODES)[keyof typeof ROLE_CODES];

export const PERMISSIONS = {
  ACCESS_ROLE_MANAGE: 'ACCESS_ROLE_MANAGE',
  ACCESS_ADMIN_MANAGE: 'ACCESS_ADMIN_MANAGE',
  AUDIT_READ: 'AUDIT_READ',
  SECURITY_SETTING_MANAGE: 'SECURITY_SETTING_MANAGE',
  SOCIETY_SETTING_MANAGE: 'SOCIETY_SETTING_MANAGE',
  RESIDENT_READ: 'RESIDENT_READ',
  RESIDENT_CREATE: 'RESIDENT_CREATE',
  RESIDENT_UPDATE: 'RESIDENT_UPDATE',
  RESIDENT_STATUS_CHANGE: 'RESIDENT_STATUS_CHANGE',
  RESIDENT_ARCHIVE: 'RESIDENT_ARCHIVE',
  RESIDENT_DOCUMENT_READ: 'RESIDENT_DOCUMENT_READ',
  RESIDENT_DOCUMENT_MANAGE: 'RESIDENT_DOCUMENT_MANAGE',
  RESIDENT_ID_CARD_MANAGE: 'RESIDENT_ID_CARD_MANAGE',
  PROPERTY_MANAGE: 'PROPERTY_MANAGE',
  BILLING_DUE_READ: 'BILLING_DUE_READ',
  BILLING_FEE_MANAGE: 'BILLING_FEE_MANAGE',
  PAYMENT_RECORD: 'PAYMENT_RECORD',
  PAYMENT_VERIFY: 'PAYMENT_VERIFY',
  PAYMENT_ADJUST: 'PAYMENT_ADJUST',
  PAYMENT_WAIVE: 'PAYMENT_WAIVE',
  PAYMENT_REVERSE: 'PAYMENT_REVERSE',
  FINANCIAL_REPORT_EXPORT: 'FINANCIAL_REPORT_EXPORT',
  STAFF_MANAGE: 'STAFF_MANAGE',
  STAFF_DOCUMENT_READ: 'STAFF_DOCUMENT_READ',
  SALARY_READ: 'SALARY_READ',
  SALARY_PAY: 'SALARY_PAY',
  SALARY_REVERSE: 'SALARY_REVERSE',
  WORKER_MANAGE: 'WORKER_MANAGE',
  WORKER_SCHEDULE: 'WORKER_SCHEDULE',
  WORKER_PERFORMANCE: 'WORKER_PERFORMANCE',
  WORKFORCE_EXPORT: 'WORKFORCE_EXPORT',
  COMPLAINT_MANAGE: 'COMPLAINT_MANAGE',
  COMPLAINT_READ: 'COMPLAINT_READ',
  COMPLAINT_SENSITIVE_READ: 'COMPLAINT_SENSITIVE_READ',
  MAINTENANCE_MANAGE: 'MAINTENANCE_MANAGE',
  MAINTENANCE_READ: 'MAINTENANCE_READ',
  TICKET_EXPORT: 'TICKET_EXPORT',
  NOTIFICATION_SEND: 'NOTIFICATION_SEND',
  NOTIFICATION_TEMPLATE_MANAGE: 'NOTIFICATION_TEMPLATE_MANAGE',
  NOTIFICATION_LOG_READ: 'NOTIFICATION_LOG_READ',
  ANNOUNCEMENT_MANAGE: 'ANNOUNCEMENT_MANAGE',
  EMERGENCY_NOTIFICATION_SEND: 'EMERGENCY_NOTIFICATION_SEND',
  NOTIFICATION_PROVIDER_MANAGE: 'NOTIFICATION_PROVIDER_MANAGE',
  REPORT_READ: 'REPORT_READ',
  REPORT_EXPORT: 'REPORT_EXPORT',
  PROFILE_CORRECTION_MANAGE: 'PROFILE_CORRECTION_MANAGE',
  VISITOR_VIEW: 'VISITOR_VIEW',
  VISITOR_CREATE: 'VISITOR_CREATE',
  VISITOR_APPROVE: 'VISITOR_APPROVE',
  VISITOR_CHECK_IN: 'VISITOR_CHECK_IN',
  VISITOR_CHECK_OUT: 'VISITOR_CHECK_OUT',
  VISITOR_ADMIN: 'VISITOR_ADMIN',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export interface AuthenticatedUser {
  id: string;
  societyId: string;
  username: string;
  displayName: string;
  forcePasswordChange: boolean;
  roles: string[];
  permissions: string[];
  csrfToken: string;
  /** Phase S2: Supabase Auth user ID (present when FEATURE_SUPABASE_AUTH=true) */
  supabaseId?: string;
}

export interface ApiErrorResponse {
  statusCode: number;
  code: string;
  message: string;
  correlationId: string;
  details?: Record<string, string[]>;
}

// Phase S3 — Supabase api schema view types
export type {
  ApiProperty,
  ApiUnit,
  ApiResident,
  ApiResidentOccupancy,
  ApiHouseholdMember,
  ApiVehicle,
  ApiResidentIdCard,
} from './supabase/api-types';
