CREATE TYPE "TicketPriority" AS ENUM ('LOW','NORMAL','HIGH','URGENT','EMERGENCY');
CREATE TYPE "ComplaintPrivacy" AS ENUM ('STANDARD','RESTRICTED','CONFIDENTIAL');
CREATE TYPE "ComplaintStatus" AS ENUM ('SUBMITTED','UNDER_REVIEW','ASSIGNED','IN_PROGRESS','WAITING_FOR_RESIDENT','RESOLVED','REJECTED','CLOSED','REOPENED');
CREATE TYPE "MaintenanceStatus" AS ENUM ('SUBMITTED','UNDER_REVIEW','APPROVED','ASSIGNED','VISIT_SCHEDULED','WORK_IN_PROGRESS','AWAITING_PARTS','WAITING_FOR_RESIDENT','COMPLETED','CANCELLED','REJECTED','REOPENED','CLOSED');
CREATE TYPE "TicketMessageVisibility" AS ENUM ('RESIDENT_VISIBLE','INTERNAL','WORKER_OPERATIONAL');
CREATE TYPE "TicketAttachmentStatus" AS ENUM ('ACTIVE','ARCHIVED');
CREATE TYPE "WorkerAssignmentStatus" AS ENUM ('ACTIVE','CANCELLED','COMPLETED');
CREATE TYPE "AppointmentStatus" AS ENUM ('PROPOSED','CONFIRMED','RESCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED','MISSED');
CREATE TYPE "TicketType" AS ENUM ('COMPLAINT','MAINTENANCE');
CREATE TYPE "EscalationKind" AS ENUM ('RESPONSE_DUE','RESPONSE_OVERDUE','RESOLUTION_DUE','RESOLUTION_OVERDUE');

CREATE TABLE "complaint_category" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"society_id" UUID NOT NULL REFERENCES "society"("id") ON DELETE RESTRICT,"name" VARCHAR(120) NOT NULL,"normalized_name" VARCHAR(120) NOT NULL,"description" VARCHAR(500),"active" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,"version" INTEGER NOT NULL DEFAULT 0,CONSTRAINT "uk_complaint_category_society_name" UNIQUE("society_id","normalized_name"));
CREATE INDEX "complaint_category_society_active_idx" ON "complaint_category"("society_id","active");
CREATE TABLE "maintenance_category" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"society_id" UUID NOT NULL REFERENCES "society"("id") ON DELETE RESTRICT,"name" VARCHAR(120) NOT NULL,"normalized_name" VARCHAR(120) NOT NULL,"description" VARCHAR(500),"worker_category_id" UUID REFERENCES "worker_category"("id") ON DELETE RESTRICT,"required_skill_id" UUID REFERENCES "worker_skill"("id") ON DELETE RESTRICT,"active" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,"version" INTEGER NOT NULL DEFAULT 0,CONSTRAINT "uk_maintenance_category_society_name" UNIQUE("society_id","normalized_name"));
CREATE INDEX "maintenance_category_society_active_idx" ON "maintenance_category"("society_id","active");
CREATE TABLE "ticket_sequence" ("society_id" UUID NOT NULL REFERENCES "society"("id") ON DELETE RESTRICT,"ticket_type" "TicketType" NOT NULL,"sequence_year" INTEGER NOT NULL,"next_value" BIGINT NOT NULL DEFAULT 1,"updated_at" TIMESTAMPTZ(6) NOT NULL,PRIMARY KEY("society_id","ticket_type","sequence_year"));

CREATE TABLE "complaint" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"society_id" UUID NOT NULL REFERENCES "society"("id") ON DELETE RESTRICT,"resident_id" UUID NOT NULL REFERENCES "resident"("id") ON DELETE RESTRICT,"property_id" UUID REFERENCES "property"("id") ON DELETE RESTRICT,"unit_id" UUID REFERENCES "unit"("id") ON DELETE RESTRICT,"category_id" UUID NOT NULL REFERENCES "complaint_category"("id") ON DELETE RESTRICT,"ticket_number" VARCHAR(80) NOT NULL,"subject" VARCHAR(180) NOT NULL,"description" TEXT NOT NULL,"location" VARCHAR(300),"resident_urgency" "TicketPriority" NOT NULL DEFAULT 'NORMAL',"priority" "TicketPriority" NOT NULL DEFAULT 'NORMAL',"privacy" "ComplaintPrivacy" NOT NULL DEFAULT 'STANDARD',"preferred_contact_method" VARCHAR(40),"status" "ComplaintStatus" NOT NULL DEFAULT 'SUBMITTED',"property_snapshot" JSONB NOT NULL DEFAULT '{}',"target_response_at" TIMESTAMPTZ(6),"target_resolution_at" TIMESTAMPTZ(6),"responded_at" TIMESTAMPTZ(6),"resolved_at" TIMESTAMPTZ(6),"closed_at" TIMESTAMPTZ(6),"archived_at" TIMESTAMPTZ(6),"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,"version" INTEGER NOT NULL DEFAULT 0,CONSTRAINT "uk_complaint_society_ticket" UNIQUE("society_id","ticket_number"));
CREATE INDEX "complaint_society_status_priority_created_idx" ON "complaint"("society_id","status","priority","created_at");
CREATE INDEX "complaint_resident_created_idx" ON "complaint"("resident_id","created_at");
CREATE INDEX "complaint_privacy_status_idx" ON "complaint"("privacy","status");

CREATE TABLE "maintenance_request" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"society_id" UUID NOT NULL REFERENCES "society"("id") ON DELETE RESTRICT,"resident_id" UUID NOT NULL REFERENCES "resident"("id") ON DELETE RESTRICT,"property_id" UUID REFERENCES "property"("id") ON DELETE RESTRICT,"unit_id" UUID REFERENCES "unit"("id") ON DELETE RESTRICT,"category_id" UUID NOT NULL REFERENCES "maintenance_category"("id") ON DELETE RESTRICT,"ticket_number" VARCHAR(80) NOT NULL,"subject" VARCHAR(180) NOT NULL,"description" TEXT NOT NULL,"exact_location" VARCHAR(300) NOT NULL,"preferred_visit_date" DATE,"preferred_start_minute" INTEGER,"preferred_end_minute" INTEGER,"access_instructions" VARCHAR(1000),"resident_urgency" "TicketPriority" NOT NULL DEFAULT 'NORMAL',"priority" "TicketPriority" NOT NULL DEFAULT 'NORMAL',"preferred_contact_method" VARCHAR(40),"contact_disclosure_consent" BOOLEAN NOT NULL DEFAULT false,"status" "MaintenanceStatus" NOT NULL DEFAULT 'SUBMITTED',"property_snapshot" JSONB NOT NULL DEFAULT '{}',"target_response_at" TIMESTAMPTZ(6),"target_resolution_at" TIMESTAMPTZ(6),"responded_at" TIMESTAMPTZ(6),"completed_at" TIMESTAMPTZ(6),"closed_at" TIMESTAMPTZ(6),"archived_at" TIMESTAMPTZ(6),"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,"version" INTEGER NOT NULL DEFAULT 0,CONSTRAINT "uk_maintenance_society_ticket" UNIQUE("society_id","ticket_number"),CHECK("preferred_start_minute" IS NULL OR "preferred_start_minute" BETWEEN 0 AND 1439),CHECK("preferred_end_minute" IS NULL OR "preferred_end_minute" BETWEEN 1 AND 1440));
CREATE INDEX "maintenance_society_status_priority_created_idx" ON "maintenance_request"("society_id","status","priority","created_at");
CREATE INDEX "maintenance_resident_created_idx" ON "maintenance_request"("resident_id","created_at");

CREATE TABLE "complaint_message" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"complaint_id" UUID NOT NULL REFERENCES "complaint"("id") ON DELETE RESTRICT,"author_user_id" UUID NOT NULL REFERENCES "user_account"("id") ON DELETE RESTRICT,"body" VARCHAR(4000) NOT NULL,"visibility" "TicketMessageVisibility" NOT NULL DEFAULT 'RESIDENT_VISIBLE',"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "complaint_message_ticket_created_idx" ON "complaint_message"("complaint_id","created_at");
CREATE TABLE "maintenance_message" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"maintenance_request_id" UUID NOT NULL REFERENCES "maintenance_request"("id") ON DELETE RESTRICT,"author_user_id" UUID NOT NULL REFERENCES "user_account"("id") ON DELETE RESTRICT,"body" VARCHAR(4000) NOT NULL,"visibility" "TicketMessageVisibility" NOT NULL DEFAULT 'RESIDENT_VISIBLE',"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "maintenance_message_ticket_created_idx" ON "maintenance_message"("maintenance_request_id","created_at");
CREATE TABLE "complaint_attachment" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"complaint_id" UUID NOT NULL REFERENCES "complaint"("id") ON DELETE RESTRICT,"message_id" UUID,"object_key" VARCHAR(500) NOT NULL UNIQUE,"original_file_name" VARCHAR(255) NOT NULL,"media_type" VARCHAR(120) NOT NULL,"size_bytes" BIGINT NOT NULL,"checksum_sha256" CHAR(64) NOT NULL,"sensitive" BOOLEAN NOT NULL DEFAULT false,"status" "TicketAttachmentStatus" NOT NULL DEFAULT 'ACTIVE',"uploaded_by_user_id" UUID NOT NULL REFERENCES "user_account"("id") ON DELETE RESTRICT,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"archived_at" TIMESTAMPTZ(6));
CREATE INDEX "complaint_attachment_ticket_status_idx" ON "complaint_attachment"("complaint_id","status");
CREATE TABLE "maintenance_attachment" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"maintenance_request_id" UUID NOT NULL REFERENCES "maintenance_request"("id") ON DELETE RESTRICT,"message_id" UUID,"object_key" VARCHAR(500) NOT NULL UNIQUE,"original_file_name" VARCHAR(255) NOT NULL,"media_type" VARCHAR(120) NOT NULL,"size_bytes" BIGINT NOT NULL,"checksum_sha256" CHAR(64) NOT NULL,"sensitive" BOOLEAN NOT NULL DEFAULT false,"status" "TicketAttachmentStatus" NOT NULL DEFAULT 'ACTIVE',"uploaded_by_user_id" UUID NOT NULL REFERENCES "user_account"("id") ON DELETE RESTRICT,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"archived_at" TIMESTAMPTZ(6));
CREATE INDEX "maintenance_attachment_ticket_status_idx" ON "maintenance_attachment"("maintenance_request_id","status");

CREATE TABLE "complaint_status_history" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"complaint_id" UUID NOT NULL REFERENCES "complaint"("id") ON DELETE RESTRICT,"from_status" "ComplaintStatus","to_status" "ComplaintStatus" NOT NULL,"resident_explanation" VARCHAR(1000),"internal_reason" VARCHAR(1000),"acted_by_user_id" UUID NOT NULL REFERENCES "user_account"("id") ON DELETE RESTRICT,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "complaint_history_ticket_created_idx" ON "complaint_status_history"("complaint_id","created_at");
CREATE TABLE "maintenance_status_history" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"maintenance_request_id" UUID NOT NULL REFERENCES "maintenance_request"("id") ON DELETE RESTRICT,"from_status" "MaintenanceStatus","to_status" "MaintenanceStatus" NOT NULL,"resident_explanation" VARCHAR(1000),"internal_reason" VARCHAR(1000),"acted_by_user_id" UUID NOT NULL REFERENCES "user_account"("id") ON DELETE RESTRICT,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "maintenance_history_ticket_created_idx" ON "maintenance_status_history"("maintenance_request_id","created_at");
CREATE TABLE "complaint_administrator_assignment" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"complaint_id" UUID NOT NULL REFERENCES "complaint"("id") ON DELETE RESTRICT,"administrator_user_id" UUID NOT NULL REFERENCES "user_account"("id") ON DELETE RESTRICT,"assigned_by_user_id" UUID NOT NULL REFERENCES "user_account"("id") ON DELETE RESTRICT,"reason" VARCHAR(500),"assigned_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"ended_at" TIMESTAMPTZ(6));
CREATE UNIQUE INDEX "complaint_one_active_admin_idx" ON "complaint_administrator_assignment"("complaint_id") WHERE "ended_at" IS NULL;

CREATE TABLE "worker_assignment" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"maintenance_request_id" UUID NOT NULL REFERENCES "maintenance_request"("id") ON DELETE RESTRICT,"worker_id" UUID NOT NULL REFERENCES "service_worker"("id") ON DELETE RESTRICT,"status" "WorkerAssignmentStatus" NOT NULL DEFAULT 'ACTIVE',"reason" VARCHAR(500) NOT NULL,"assigned_by_user_id" UUID NOT NULL REFERENCES "user_account"("id") ON DELETE RESTRICT,"assigned_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"ended_at" TIMESTAMPTZ(6),"version" INTEGER NOT NULL DEFAULT 0);
CREATE UNIQUE INDEX "maintenance_one_active_worker_idx" ON "worker_assignment"("maintenance_request_id") WHERE "status"='ACTIVE';
CREATE INDEX "worker_assignment_worker_status_idx" ON "worker_assignment"("worker_id","status");
CREATE TABLE "maintenance_appointment" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"maintenance_request_id" UUID NOT NULL REFERENCES "maintenance_request"("id") ON DELETE RESTRICT,"worker_assignment_id" UUID NOT NULL REFERENCES "worker_assignment"("id") ON DELETE RESTRICT,"worker_id" UUID NOT NULL REFERENCES "service_worker"("id") ON DELETE RESTRICT,"reservation_id" UUID REFERENCES "worker_schedule_reservation"("id") ON DELETE RESTRICT,"starts_at" TIMESTAMPTZ(6) NOT NULL,"ends_at" TIMESTAMPTZ(6) NOT NULL,"status" "AppointmentStatus" NOT NULL DEFAULT 'PROPOSED',"access_instructions" VARCHAR(1000),"change_reason" VARCHAR(500),"created_by_user_id" UUID NOT NULL REFERENCES "user_account"("id") ON DELETE RESTRICT,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,"version" INTEGER NOT NULL DEFAULT 0,CHECK("ends_at">"starts_at"));
CREATE INDEX "appointment_request_starts_idx" ON "maintenance_appointment"("maintenance_request_id","starts_at");
CREATE INDEX "appointment_worker_status_starts_idx" ON "maintenance_appointment"("worker_id","status","starts_at");
ALTER TABLE "maintenance_appointment" ADD CONSTRAINT "maintenance_appointment_no_overlap" EXCLUDE USING gist ("worker_id" WITH =,tstzrange("starts_at","ends_at",'[)') WITH &&) WHERE ("status" IN ('PROPOSED','CONFIRMED','RESCHEDULED','IN_PROGRESS'));

CREATE TABLE "maintenance_resolution" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"maintenance_request_id" UUID NOT NULL UNIQUE REFERENCES "maintenance_request"("id") ON DELETE RESTRICT,"worker_id" UUID NOT NULL REFERENCES "service_worker"("id") ON DELETE RESTRICT,"work_performed" VARCHAR(4000) NOT NULL,"resident_summary" VARCHAR(2000) NOT NULL,"parts_notes" VARCHAR(2000),"internal_notes" VARCHAR(2000),"follow_up_recommendation" VARCHAR(1000),"completed_at" TIMESTAMPTZ(6) NOT NULL,"verified_by_user_id" UUID REFERENCES "user_account"("id") ON DELETE RESTRICT,"resident_confirmed_at" TIMESTAMPTZ(6),"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,"version" INTEGER NOT NULL DEFAULT 0);
CREATE TABLE "service_rating" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"maintenance_request_id" UUID NOT NULL UNIQUE REFERENCES "maintenance_request"("id") ON DELETE RESTRICT,"resident_id" UUID NOT NULL REFERENCES "resident"("id") ON DELETE RESTRICT,"worker_id" UUID NOT NULL REFERENCES "service_worker"("id") ON DELETE RESTRICT,"overall" INTEGER NOT NULL,"service_quality" INTEGER NOT NULL,"timeliness" INTEGER NOT NULL,"professional_behaviour" INTEGER NOT NULL,"comments" VARCHAR(1000),"confidential_comments" VARCHAR(1000),"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,"version" INTEGER NOT NULL DEFAULT 0,CHECK("overall" BETWEEN 1 AND 5 AND "service_quality" BETWEEN 1 AND 5 AND "timeliness" BETWEEN 1 AND 5 AND "professional_behaviour" BETWEEN 1 AND 5));
CREATE INDEX "service_rating_worker_created_idx" ON "service_rating"("worker_id","created_at");

CREATE TABLE "service_level_policy" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"society_id" UUID NOT NULL REFERENCES "society"("id") ON DELETE RESTRICT,"ticket_type" "TicketType" NOT NULL,"category_id" UUID,"priority" "TicketPriority" NOT NULL,"response_minutes" INTEGER NOT NULL,"resolution_minutes" INTEGER NOT NULL,"escalation_role_code" VARCHAR(80) NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,"version" INTEGER NOT NULL DEFAULT 0,CHECK("response_minutes">0 AND "resolution_minutes">0));
CREATE UNIQUE INDEX "uk_sla_policy_scope" ON "service_level_policy"("society_id","ticket_type",COALESCE("category_id",'00000000-0000-0000-0000-000000000000'::uuid),"priority");
CREATE INDEX "sla_policy_society_active_idx" ON "service_level_policy"("society_id","active");
CREATE TABLE "escalation_record" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"complaint_id" UUID REFERENCES "complaint"("id") ON DELETE RESTRICT,"maintenance_request_id" UUID REFERENCES "maintenance_request"("id") ON DELETE RESTRICT,"kind" "EscalationKind" NOT NULL,"escalation_role_code" VARCHAR(80) NOT NULL,"idempotency_key" VARCHAR(180) NOT NULL UNIQUE,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,CHECK(("complaint_id" IS NOT NULL)::int+("maintenance_request_id" IS NOT NULL)::int=1));
CREATE INDEX "escalation_complaint_created_idx" ON "escalation_record"("complaint_id","created_at");
CREATE INDEX "escalation_maintenance_created_idx" ON "escalation_record"("maintenance_request_id","created_at");
CREATE TABLE "contact_disclosure_log" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"maintenance_request_id" UUID NOT NULL REFERENCES "maintenance_request"("id") ON DELETE RESTRICT,"recipient_type" VARCHAR(30) NOT NULL,"recipient_id" UUID NOT NULL,"disclosed_fields" JSONB NOT NULL,"policy_basis" VARCHAR(500) NOT NULL,"acted_by_user_id" UUID REFERENCES "user_account"("id") ON DELETE RESTRICT,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "disclosure_request_created_idx" ON "contact_disclosure_log"("maintenance_request_id","created_at");
